name: AxEnvoy
version: '${project.version}'
main: com.artillexstudios.axenvoy.AxEnvoyPlugin
api-version: "1.19"
dependencies:
  server:
    DecentHolograms:
      required: false
      load: BEFORE
    PlaceholderAPI:
      required: false
      load: BEFORE
    Multiverse-Core:
      required: false
      load: BEFORE
    WorldGuard:
      required: false
      load: BEFORE