name: AxEnvoy
version: '${project.version}'
main: com.artillexstudios.axenvoy.AxEnvoyPlugin
api-version: 1.18
softdepend:
  - PlaceholderAPI
  - Multiverse-Core
  - WorldGuard
  - ItemsAdder
  - Oraxen