crates:
  # The name of the crate:the spawn chance of the crate spawning
  common: 50
  legendary: 30
  rare: 20

amount: 30
collect-cooldown: 10 # Seconds
collect-global-cooldown: false # Whether the cooldown should be for all crates of this envoy, or per-crate
broadcast-collect: true
timeout-time: 300 # This is in seconds
every: "1h" # Start an envoy event every hour. To disable, leave as ""
alert-times: # Time before every
  - "30m"
  - "10m"
  - "5s"
  - "3s"
  - "2s"
  - "1s"

min-players: 2 # Minimum players required for autostart

random-spawn:
  enabled: true # Should we use random spawning?
  center: "world;0;100;0" # The center location
  min-distance: 20 # The minimum distance from the center an envoy may spawn
  max-distance: 100 # The maximum distance from the center an envoy may spawn
  min-height: 10 # The minimum height at which an envoy may spawn
  max-height: 200 # The maximum height at which an envoy may spawn

  # You can use RegEx here, to match the name of the block
  # For a list of materials, visit: https://jd.papermc.io/paper/1.20/org/bukkit/Material.html
  not-on-blocks:
    - "(?<!s)t?air(?!s)"
    - "(leaves)"
    - "(sign)"
    - "diamond_block"

# You can override messages from messages.yml. You need to put it exactly how it is in that file.
messages:
  prefix: "<#00FFAA>&lAxEnvoy &7» "

rewards:
  use-prefix: true # If we should use prefix for message rewards of this envoy

flare:
  enabled: true
  cooldown: 30 # Cooldown in seconds
  item:
    material: "prismarine_shard"
    name: "&cEnvoy flare"
    glow: true
    custom-model-data: 0
    lore:
      - "&7Right click with this, to start"
      - "&7the default envoy!"

pre-defined-spawns:
  enabled: false
  locations:
    - "world;1;1;1"